# Author: Umesh S & Sharif Sultan

From openjdk:8
copy target/SettingsService-0.0.1-SNAPSHOT.jar SettingsService-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","SettingsService-0.0.1-SNAPSHOT.jar"]
EXPOSE 8093

