pipeline {
      environment {
        registry = "shrey21s/petzeypatient"
        registryCredential = "1"
        dockerImage = ''
    }
    agent any

    stages {

        stage ('Artifacts') {
            steps {
                script{
                    sh 'mvn clean install'
                }  
            }
        }

    stage('Sonarqube'){
       steps{
         echo "Sonarqube codequality"
         sh '''
            mvn clean verify sonar:sonar \
            -Dsonar.projectKey=Petzey-Patient \
            -Dsonar.host.url=https://codequality.cmd.skillassure.com \
            -Dsonar.login=sqp_a927a2f11f9363f958a674964384006a58491d00
         '''
       }
    }

        stage ('Build Docker image') {
            steps {
                script{
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }  
            }
        }
    stage('Push docker image'){
      steps{
        echo "Pushing docker image"
        script{
           docker.withRegistry('',registryCredential) {
            dockerImage.push()
            dockerImage.push('latest')
                                }
             }
               }
            }

    
  
    }


}
