server:
  port: 8095

spring:
  application:
    name: API-ZUUL-GATEWAY

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


  instance:
    hostname: localhost

zuul:
  routes:
    SETTING-SERVICE:
      path: /api/setting-service/**
      url: http://localhost:8093

    PET-SERVICE:
      path: /api/pet-service/**
      url: http://localhost:8092

    APPOINTMENT-SERVICE:
      path: /api/appointment-service/**
      url: http://localhost:8091

    AUTH-SERVICE:
      path: /api/auth-service/**
      url: http://localhost:8094